#!/bin/bash -
# findz--Find Zombie processes and parent PID
# JP, 2021-01-23 Sat, 2021-03-28 Sun
# $Id: findz 2246 2026-01-31 21:52:25Z root $

# Find and show Zombies
zombies=$(ps -xal | egrep '^F\b|\bZl?\b')
echo 'Zombie processes:'
echo "$zombies"
echo ''

# Find and show PPIDs
echo 'Zombie process Parent PID (PPID) to kill:'
ppids=$(echo "$zombies" | awk '! /PPID/ {print $4}' | sort -u)
for ppid in $ppids; do
    ps uwx -q $ppid
    echo ''
done

# Linux Cookbook 2nd, ch20:
# You can’t kill zombies because they are already dead. They use a minuscule bit of system resources, but if you want to try getting rid of them, try sending them a SIGCHLD:
# $ sudo kill -s SIGCHLD 1299
